// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch1 = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_Switch1, 161);
    lv_obj_set_height(ui_Switch1, 52);
    lv_obj_set_x(ui_Switch1, 0);
    lv_obj_set_y(ui_Switch1, -145);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);


    ui_Arc1 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Arc1, 216);
    lv_obj_set_height(ui_Arc1, 204);
    lv_obj_set_x(ui_Arc1, 6);
    lv_obj_set_y(ui_Arc1, 74);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 50);



}
